# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-22 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0003_message_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='userlikes',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ulikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
