# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-19 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_scorepollitemsbymonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorepollitemsbymonth',
            name='nega',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorepollitemsbymonth',
            name='posi',
            field=models.IntegerField(default=0),
        ),
    ]
