# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-19 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20171119_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorepollitemsbymonth',
            name='p_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PollItem'),
        ),
    ]
