# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-22 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_scoreuserbymonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorepollitemsbymonth',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
