# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-22 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20171222_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorepollitemsbymonth',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
