# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-12 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20180306_0953'),
        ('analytics', '0008_auto_20171222_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usercon', models.CharField(max_length=100)),
                ('postissue', models.CharField(max_length=30)),
                ('postissuemsg', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('p_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PollItem')),
            ],
        ),
    ]
