# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-18 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_postreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewpolltypeunique',
            name='ecount',
            field=models.IntegerField(default=0),
        ),
    ]
