# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-23 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_viewpolltypeunique_ecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='add_days',
            field=models.IntegerField(default=0),
        ),
    ]
