# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 01:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0012_auto_20180517_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreport',
            name='Puser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
