# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-22 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0013_postreport_puser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controlname', models.CharField(max_length=60, null=True)),
                ('postadddelay', models.IntegerField(default=0)),
                ('signupdays', models.IntegerField(default=0)),
                ('removepostdvotes', models.IntegerField(default=0)),
                ('freedaysreferral', models.IntegerField(default=0)),
                ('notiweekday', models.IntegerField(default=0)),
                ('notihour', models.IntegerField(default=0)),
                ('notiminute', models.IntegerField(default=0)),
                ('delaypopsurvey', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingPromo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoname', models.CharField(max_length=60, null=True)),
                ('promotype', models.CharField(blank=True, max_length=60, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('promoid', models.CharField(default='None', max_length=6, null=True)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromoAnalytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoname', models.CharField(max_length=60, null=True)),
                ('promotype', models.CharField(blank=True, max_length=60, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ref_id', models.CharField(max_length=6, null=True)),
                ('promouser', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promouser', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
