# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-11 01:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceToDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=120)),
                ('cashprice', models.IntegerField(default=0)),
                ('daystoadd', models.IntegerField(default=0)),
                ('subplan', models.CharField(max_length=120, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=100, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100, null=True)),
                ('adddays', models.IntegerField(default=0)),
                ('transaction_id', models.CharField(default='', max_length=120)),
                ('success', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
