# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-15 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetodays',
            name='cashprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, null=True),
        ),
    ]
