# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-15 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20180515_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='adddays',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='success',
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='transaction',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='startdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
