# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-30 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pollitem_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollitem',
            name='amzurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
