# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-31 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_pollitem_amzurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptype',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
