# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-09 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20171031_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollitem',
            name='imgatt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pollitem',
            name='textatt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
