# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-15 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20171112_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollitem',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
