# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-23 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20171115_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptype',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
