# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-17 08:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0012_auto_20180306_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typePoll', models.CharField(blank=True, choices=[('SG', 'Suggestions'), ('RS', 'Recommendations')], default=None, max_length=20)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('allowed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(default=0)),
                ('user_submit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vote_user', models.ManyToManyField(blank=True, default=None, related_name='vote_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
