# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-18 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_suggestedpoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedpoll',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='suggestedpoll',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
