# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-22 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20180418_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollitem',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
