# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-25 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20180425_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedpoll',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
