# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-23 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_pollvoting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollitem',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
