# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-02 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20180523_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptype',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=150, null=True, unique=True),
        ),
    ]
