# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20180608_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptype',
            name='freepoll',
            field=models.BooleanField(default=False),
        ),
    ]
