# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_ptype_freepoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollitem',
            name='modifieddate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
