# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-23 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20190122_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollitem',
            name='pollmodifydate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
