# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-24 01:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0003_topicpoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicpoll',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topicpoll',
            name='tagfav',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
