# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-13 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firebasenotifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetoken',
            options={'ordering': ('created',)},
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
