# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-20 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebasenotifications', '0003_auto_20181213_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
