# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-22 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='pollitem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.PollItem'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='pollreview',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='polltype',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Ptype'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tagpoll',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.TagPoll'),
        ),
    ]
