# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-11 06:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, max_length=2048, null=True, upload_to=users.models.image_upload_to)),
                ('rank', models.CharField(blank=True, max_length=60, null=True)),
                ('score', models.IntegerField(default=0)),
                ('banned', models.BooleanField(default=False)),
                ('trial', models.BooleanField(default=False)),
                ('subscribe', models.BooleanField(default=True)),
                ('member', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
