# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-11 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puser',
            name='subscribe',
        ),
        migrations.AddField(
            model_name='puser',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='puser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='puser',
            name='invoiceno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='puser',
            name='plan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='puser',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='puser',
            name='subenddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puser',
            name='subnewsletter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='puser',
            name='substartdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
