# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-22 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180411_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
