# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-23 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180422_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puser',
            name='invoiceno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
