# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-30 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180423_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='puser',
            name='alt_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='puser',
            name='freedays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='puser',
            name='usermaxscore',
            field=models.IntegerField(default=0),
        ),
    ]
