# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-18 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180512_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='puser',
            name='referralid',
            field=models.CharField(default='None', max_length=6),
        ),
    ]
